# Generated by Django 5.2.5 on 2025-08-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bulk_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
