# Generated by Django 5.2.5 on 2025-08-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', help_text='Product description'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default='', help_text='Add features, one per line'),
        ),
    ]
