# Generated by Django 5.2.5 on 2025-09-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('papers', 'Papers & Notebooks'), ('calculators', 'Calculators'), ('staplers', 'Staplers'), ('pens', 'Pens'), ('scissors', 'Scissors')], default='papers', max_length=50),
        ),
    ]
