# Generated by Django 5.2.5 on 2025-09-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('papers', 'Papers & Notebooks'), ('calculators', 'Calculators'), ('staplers', 'Staplers'), ('pens', 'Pens'), ('scissors', 'Scissors')], max_length=50),
        ),
    ]
